
import { Article, Language, StudentClass, Quote } from './types';

export const INTERESTS = ['Sports', 'Football', 'Chess', 'Anime', 'Music', 'Design', 'Coding', 'Cooking', 'Cars', 'Business', 'Gaming', 'Movies', 'Art', 'Fitness', 'Science'];
export const CLASSES: StudentClass[] = ['7A', '7B', '8A', '8B', '9A', '9B', '10A', '10B', '11A', '11B'];

export const INITIAL_ARTICLES: Article[] = [
  { id: 'p1', subject: 'Physics', title: 'Momentum in Sports', content: 'Physics isn\'t just in books. When a player kicks a ball, the conservation of momentum is what makes it soar...', author: 'Dr. Newton', icon: '⚛️' },
  { id: 'a1', subject: 'Algebra', title: 'The Algorithm of Life', content: 'Variables are empty slots waiting for purpose. Solving for X is solving for the unknown in your future...', author: 'Al-Khwarizmi', icon: '📐' },
  { id: 'e1', subject: 'English', title: 'Persuasive Flows', content: 'In English, flow is everything. It’s not about words, it’s about the rhythm of logic...', author: 'Shakespeare', icon: '✍️' },
  { id: 'b1', subject: 'Biology', title: 'The Logic of Cells', content: 'Every cell in your body is a tiny computer executing instructions. Understanding biology is understanding the ultimate software...', author: 'Darwin', icon: '🧬' },
  { id: 'c1', subject: 'Chemistry', title: 'Atomic Bonds', content: 'Chemistry is the study of relationships. How atoms choose to bond or repel is the foundation of everything we touch...', author: 'Curie', icon: '🧪' },
  { id: 'h1', subject: 'History', title: 'Patterns of Time', content: 'History doesn\'t repeat, but it rhymes. Recognizing the patterns of the past allows us to predict the flows of the future...', author: 'Herodotus', icon: '📜' }
];

export const INITIAL_QUOTES: Quote[] = [
  { id: 'q1', text: "The future of learning isn't more books, it's better thinking.", author: "ThinkFlow Core", category: "education" },
  { id: 'q2', text: "Education is not the learning of facts, but the training of the mind to think.", author: "Albert Einstein", category: "thinking" },
  { id: 'q3', text: "The important thing is not to stop questioning.", author: "Albert Einstein", category: "science" },
  { id: 'q4', text: "I have no special talent. I am only passionately curious.", author: "Albert Einstein", category: "learning" }
];

export const TRANSLATIONS = {
  en: {
    hero: "Think Better, Not Faster.",
    sub: "ThinkFlow is a global EdTech platform that switches your brain from memorizing to understanding.",
    features: "What's Inside?",
    feat1: "Concept Teacher: Learns your interests and explains topics through them.",
    feat2: "Thinking Coach: Uses Socratic method—asks questions instead of giving answers.",
    feat3: "Adaptive Trainer: Personalized challenges that grow with your logic.",
    start: "Get Started", login: "Login", register: "Register", logout: "Logout",
    dash: "Dashboard", teacher: "Concept Teacher", coach: "Thinking Coach", trainer: "Adaptive Trainer",
    wall: "Hall of Fame", profile: "Profile", admin: "Admin",
    save: "Apply Changes", reviews: "Community Reviews", history: "Recent Sessions",
    authError: "Access Denied. Check your credentials.",
    writeReview: "Share your experience", submit: "Post",
    theme: "Toggle Theme",
    language: "Language",
    editProfile: "Edit Profile",
    name: "Full Name", bio: "Bio", update: "Update Profile",
    tasks: "Tasks", progress: "Progress", articles: "Articles", tips: "Tips", quotes: "Quotes", leaderboard: "Leaderboard", settings: "Settings",
    learn: "Learn",
    easy: "Easy", medium: "Medium", challenge: "Challenge",
    complete: "Complete", pending: "Pending",
    xp: "XP", level: "Level",
    sat: "SAT Tips", ielts: "IELTS Tips",
    satTips: "SAT study strategies, time management, math tricks, reading strategies.",
    ieltsTips: "Speaking tips, writing tips, listening strategies, reading strategies, band score advice.",
    nextGenAI: "Next-Gen AI Education",
    beyondGenius: "Beyond Genius",
    heroSub: "ThinkFlow is more than a chat. It's your personal genius lab where AI constructs knowledge maps tailored specifically for you.",
    demo: "Demo",
    coreEngine: "The Core Engine",
    coreEngineSub: "Powered by Advanced Neural Architectures",
    stopMemorizing: "Stop Memorizing.",
    startFlowing: "Start Flowing.",
    retentionRate: "Retention Rate",
    learningSpeed: "Learning Speed",
    secure: "Secure",
    global: "Global",
    exploreSystem: "Explore System",
    reactorTitle: "AI Reactor",
    reactorDesc: "Synthesize knowledge through your interests. We don't give answers, we create understanding.",
    geniusModeTitle: "Genius Mode",
    geniusModeDesc: "Adaptive interface that adjusts to your learning rhythm.",
    biometricsTitle: "Brain Biometrics",
    biometricsDesc: "Real-time cognitive progress tracking.",
    hubTitle: "Global Hub",
    hubDesc: "Ecosystem for the world's best minds. Learn together.",
    constructingKnowledge: "Constructing Knowledge...",
    architectingModel: "Architecting your mental model for",
    geniusLabSub: "Enter any topic you want to master. Our AI will architect a custom learning path using your interests as metaphors.",
    initialize: "Initialize",
    deepUnderstanding: "Deep Understanding",
    deepUnderstandingDesc: "No rote memorization. Pure logic.",
    personalizedMetaphors: "Personalized Metaphors",
    personalizedMetaphorsDesc: "Learn physics through football.",
    skillMastery: "Skill Mastery",
    skillMasteryDesc: "Step-by-step architectural path.",
    knowledgeMap: "Knowledge Map",
    newTopic: "New Topic",
    nodeExplanation: "Node Explanation",
    theMetaphor: "The Metaphor",
    geniusChallenge: "Genius Challenge",
    completeChallenge: "Complete Challenge",
    askSidekick: "Ask AI Sidekick",
    architectingMind: "Architecting your mind",
    previous: "Previous",
    next: "Next",
    askAbout: "Ask about",
    tipsSub: "Expert advice and strategies to help you master international exams and improve your reasoning skills.",
    generalTips: "General Tips",
    generalTipsSub: "Universal advice for effective learning.",
    proTipTitle: "Pro Tip: The Socratic Loop",
    proTipDesc: "When studying, don't just read the answer. Ask yourself \"Why?\" three times. If you can explain the logic to a 5-year-old, you've truly mastered the concept. ThinkFlow is designed to help you build this habit.",
    reasoning: "Reasoning",
    logic: "Logic",
    mastery: "Mastery",
    articlesSub: "Deep dives into core concepts and reasoning.",
    philosophy: "The future of learning isn't more books, it's better thinking.",
    philosophySub: "ThinkFlow Core Philosophy",
    retentionRateLabel: "Retention Rate",
    learningSpeedLabel: "Learning Speed",
    geniusLab: "Genius Lab",
    geniusMode: "Genius Mode",
    searchThoughts: "Search thoughts...",
    globalXP: "Global XP",
    masterTopic: "What do you want to master?",
    educationBroken: "Traditional education is broken. It rewards memory, not logic. ThinkFlow changes the game, using AI to map complex concepts directly onto your neural pathways.",
    navFeatures: "Features",
    navMission: "Mission",
    navContact: "Contact Me",
    versionBadge: "V.2.0 IS NOW LIVE",
    heroThink: "Think",
    heroBeyond: "Beyond",
    heroGenius: "Genius",
    coreArchitecture: "Core Architecture",
    marqueeText: "ADAPTIVE LEARNING • NEURAL ARCHITECTURE • QUANTUM LOGIC • SOCRATIC METHOD • 3.5X FASTER • DATA RETENTION • GENIUS ENGINE",
    builtEra: "Built for the",
    nextEra: "Next Era",
    builtEraSub: "We don't teach facts. We construct bridges between complex concepts and your personal world.",
    joinRevolution: "Join the Revolution",
    ourMission: "Our Mission",
    missionStop: "Stop",
    missionMemorizing: "Memorizing.",
    missionStart: "Start",
    missionGrowing: "Growing.",
    missionSub: "Conventional education forces you to swallow data without context. ThinkFlow flips the script. We map your interests to academic challenges, creating a \"Flow State\" where learning feels as natural as breathing.",
    speedBoost: "Speed Boost",
    retention: "Retention",
    readyToAscend: "Ready to Ascend?",
    privacy: "Privacy",
    security: "Security",
    contactFooter: "Contact",
    copyright: "© 2026 THE FUTURE OF INTELLIGENCE",
    contactMeSection: "Contact Me Directly",
    contactMeSub: "Have questions or want to collaborate? I'm always open to new ideas.",
    telegramButton: "Chat on Telegram",
    tasksSub: "Personalized challenges to grow your logic.",
    clearAll: "Clear All",
    generateNewTask: "Generate New Task",
    noTasks: "No tasks yet. Generate one!",
    taskAnswerPlaceholder: "Enter the result, formula, or specific term here...",
    verifying: "Verifying...",
    submitVerify: "Submit & Verify",
    neuralMapping: "Neural Mapping...",
    synthesizingNode: "SYNTHESIZING SCIENTIFIC NODE:",
    systemOptimizing: "SYSTEM_OPTIMIZING",
    systemFailure: "System Failure",
    tryAgain: "Try Again",
    rewardLabel: "REWARD",
    geniusAnswerPlaceholder: "Enter your final answer here (e.g., '42', 'NaCl', 'F=ma'). Be precise!",
    verifyingAI: "Verifying by AI...",
    submitVerification: "Submit for Verification",
    nodeMastered: "Node Mastered",
    geniusModeActive: "GENIUS MODE ACTIVE",
    totalXP: "Total XP",
    currentLevelLabel: "Current Level",
    tasksDone: "Tasks Done",
    globalRank: "Global Rank",
    progressSub: "Your intellectual growth journey tracked in real-time.",
    levelLabel: "Level",
    nextLevel: "Next Level",
    xpNextLevel: "XP to next level",
    growthRate: "Growth Rate",
    dailyStreak: "Daily Streak",
    focusScore: "Focus Score",
    thisWeek: "this week",
    days: "Days",
    newConversation: "New Conversation",
    chatPlaceholder: "Type your thought and wait for AI...",
    thinkFlow: "ThinkFlow",
    unleashPotential: "Unleash your cognitive potential with AI-driven personalized learning.",
    topicToLearn: "Topic to Learn",
    yourInterests: "Your Interests (comma separated)",
    generateExplanation: "Generate Explanation",
    waitingInput: "Waiting for input...",
    aiThinking: "AI is thinking...",
    learningGoals: "Learning Goals",
    initializing: "Initializing ThinkFlow",
    settingUpProfile: "Setting up your profile...",
    demoMode: "DEMO MODE",
    googleSignIn: "SIGN IN WITH GOOGLE",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    encryptionActive: "Quantum Encryption Active",
    geniusEcosystem: "Genius Ecosystem",
    emailAddress: "Email Address",
    password: "Password"
  },
  ru: {
    hero: "Думай лучше, а не быстрее.",
    sub: "ThinkFlow — это глобальная EdTech платформа, которая переключает ваш мозг с запоминания на понимание.",
    features: "Что внутри?",
    feat1: "Учитель Концептов: Объясняет темы через твои интересы (футбол, аниме, код).",
    feat2: "Коуч Мышления: Сократовский метод — учит тебя находить ответы самому.",
    feat3: "Адаптивный Тренер: Задачи, которые подстраиваются под твой уровень логики.",
    start: "Начать", login: "Войти", register: "Регистрация", logout: "Выйти",
    dash: "Главная", teacher: "Учитель концептов", coach: "Коуч мышления", trainer: "Адаптивный тренер",
    wall: "Зал славы", profile: "Профиль", admin: "Админ",
    save: "Сохранить", reviews: "Отзывы сообщества", history: "История сессий",
    authError: "Доступ запрещен. Проверьте данные.",
    writeReview: "Поделитесь опытом", submit: "Опубликовать",
    theme: "Сменить тему",
    language: "Язык",
    editProfile: "Редактор профиля",
    name: "ФИО", bio: "О себе", update: "Обновить профиль",
    tasks: "Задания", progress: "Прогресс", articles: "Статьи", tips: "Советы", quotes: "Цитаты", leaderboard: "Лидерборд", settings: "Настройки",
    learn: "Обучение",
    easy: "Легко", medium: "Средне", challenge: "Вызов",
    complete: "Завершено", pending: "В процессе",
    xp: "Опыт", level: "Уровень",
    sat: "Советы по SAT", ielts: "Советы по IELTS",
    satTips: "Стратегии подготовки к SAT, тайм-менеджмент, математические трюки.",
    ieltsTips: "Советы по говорению, письму, аудированию и чтению IELTS.",
    nextGenAI: "Новое поколение ИИ",
    beyondGenius: "За гранью гениальности",
    heroSub: "ThinkFlow — это не просто чат. Это ваша персональная лаборатория гениальности, где ИИ строит карты знаний специально для вас.",
    demo: "Демо",
    coreEngine: "Ядро системы",
    coreEngineSub: "На базе передовых нейронных архитектур",
    stopMemorizing: "Хватит зубрить.",
    startFlowing: "Начни понимать.",
    retentionRate: "Уровень удержания",
    learningSpeed: "Скорость обучения",
    secure: "Безопасно",
    global: "Глобально",
    exploreSystem: "Изучить систему",
    reactorTitle: "ИИ-Реактор",
    reactorDesc: "Синтез знаний через ваши интересы. Мы не даем ответы, мы создаем понимание.",
    geniusModeTitle: "Гениальный Режим",
    geniusModeDesc: "Адаптивный интерфейс, который подстраивается под ваш ритм обучения.",
    biometricsTitle: "Биометрия Мозга",
    biometricsDesc: "Отслеживание когнитивного прогресса в реальном времени.",
    hubTitle: "Глобальный Хаб",
    hubDesc: "Экосистема для лучших умов планеты. Учитесь вместе.",
    constructingKnowledge: "Построение знаний...",
    architectingModel: "Проектирование ментальной модели для",
    geniusLabSub: "Введите любую тему, которую хотите освоить. Наш ИИ построит индивидуальный путь обучения, используя ваши интересы в качестве метафор.",
    initialize: "Инициализировать",
    deepUnderstanding: "Глубокое понимание",
    deepUnderstandingDesc: "Никакой зубрежки. Чистая логика.",
    personalizedMetaphors: "Персональные метафоры",
    personalizedMetaphorsDesc: "Изучайте физику через футбол.",
    skillMastery: "Мастерство навыков",
    skillMasteryDesc: "Пошаговый архитектурный путь.",
    knowledgeMap: "Карта знаний",
    newTopic: "Новая тема",
    nodeExplanation: "Объяснение узла",
    theMetaphor: "Метафора",
    geniusChallenge: "Вызов гения",
    completeChallenge: "Завершить вызов",
    askSidekick: "Спросить ИИ-помощника",
    architectingMind: "Проектирование вашего разума",
    previous: "Назад",
    next: "Далее",
    askAbout: "Спросить о",
    tipsSub: "Экспертные советы и стратегии, которые помогут вам сдать международные экзамены и развить навыки мышления.",
    generalTips: "Общие советы",
    generalTipsSub: "Универсальные советы для эффективного обучения.",
    proTipTitle: "Про-совет: Сократовская петля",
    proTipDesc: "При обучении не просто читайте ответ. Спросите себя «Почему?» три раза. Если вы можете объяснить логику 5-летнему ребенку, значит, вы действительно освоили концепцию. ThinkFlow поможет вам выработать эту привычку.",
    reasoning: "Мышление",
    logic: "Логика",
    mastery: "Мастерство",
    articlesSub: "Глубокое погружение в основные концепции и рассуждения.",
    philosophy: "Будущее обучения — это не больше книг, а лучшее мышление.",
    philosophySub: "Основная философия ThinkFlow",
    retentionRateLabel: "Уровень удержания",
    learningSpeedLabel: "Скорость обучения",
    geniusLab: "Лаборатория Гения",
    geniusMode: "Режим Гения",
    searchThoughts: "Поиск мыслей...",
    globalXP: "Глобальный XP",
    masterTopic: "Что вы хотите изучить?",
    educationBroken: "Традиционное образование сломано. Оно вознаграждает память, а не логику. ThinkFlow меняет правила игры, используя ИИ для отображения сложных концепций непосредственно на ваши нейронные пути.",
    navFeatures: "Функции",
    navMission: "Миссия",
    navContact: "Связаться со мной",
    versionBadge: "V.2.0 УЖЕ ДОСТУПНА",
    heroThink: "Думай",
    heroBeyond: "Сверх",
    heroGenius: "Гения",
    coreArchitecture: "Ядро Системы",
    marqueeText: "АДАПТИВНОЕ ОБУЧЕНИЕ • НЕЙРОННАЯ АРХИТЕКТУРА • КВАНТОВАЯ ЛОГИКА • СОКРАТОВСКИЙ МЕТОД • В 3.5 РАЗА БЫСТРЕЕ • УДЕРЖАНИЕ ДАННЫХ • ГЕНИАЛЬНЫЙ ДВИЖОК",
    builtEra: "Создано для",
    nextEra: "Новой Эры",
    builtEraSub: "Мы не учим фактам. Мы строим мосты между сложными концепциями и вашим личным миром.",
    joinRevolution: "Присоединиться к революции",
    ourMission: "Наша Миссия",
    missionStop: "Хватит",
    missionMemorizing: "Зубрить.",
    missionStart: "Начни",
    missionGrowing: "Расти.",
    missionSub: "Традиционное образование заставляет вас поглощать данные без контекста. ThinkFlow меняет правила игры. Мы привязываем ваши интересы к учебным задачам, создавая «состояние потока», где обучение кажется естественным, как дыхание.",
    speedBoost: "Ускорение",
    retention: "Удержание",
    readyToAscend: "Готовы к восхождению?",
    privacy: "Приватность",
    security: "Безопасность",
    contactFooter: "Контакты",
    copyright: "© 2026 БУДУЩЕЕ ИНТЕЛЛЕКТА",
    contactMeSection: "Связаться напрямую",
    contactMeSub: "Есть вопросы или предложения? Я всегда открыт для новых идей.",
    telegramButton: "Написать в Telegram",
    tasksSub: "Персонализированные задачи для развития вашей логики.",
    clearAll: "Очистить всё",
    generateNewTask: "Создать новое задание",
    noTasks: "Заданий пока нет. Создайте первое!",
    taskAnswerPlaceholder: "Введите результат, формулу или конкретный термин приглашая...",
    verifying: "Проверка...",
    submitVerify: "Отправить и проверить",
    neuralMapping: "Нейронное картирование...",
    synthesizingNode: "СИНТЕЗ НАУЧНОГО УЗЛА:",
    systemOptimizing: "ОПТИМИЗАЦИЯ СИСТЕМЫ",
    systemFailure: "Системный сбой",
    tryAgain: "Попробовать снова",
    rewardLabel: "НАГРАДА",
    geniusAnswerPlaceholder: "Введите ваш окончательный ответ здесь (например, '42', 'NaCl', 'F=ma'). Будьте точны!",
    verifyingAI: "Проверка ИИ...",
    submitVerification: "Отправить на проверку",
    nodeMastered: "Узел освоен",
    geniusModeActive: "ГЕНИАЛЬНЫЙ РЕЖИМ АКТИВЕН",
    totalXP: "Всего XP",
    currentLevelLabel: "Текущий уровень",
    tasksDone: "Задач выполнено",
    globalRank: "Мировой рейтинг",
    progressSub: "Ваш путь интеллектуального роста в реальном времени.",
    levelLabel: "Уровень",
    nextLevel: "Следующий уровень",
    xpNextLevel: "XP до следующего уровня",
    growthRate: "Темп роста",
    dailyStreak: "Дней подряд",
    focusScore: "Очки фокуса",
    thisWeek: "на этой неделе",
    days: "дн.",
    newConversation: "Новый разговор",
    chatPlaceholder: "Введите вашу мысль и подождите ответа ИИ...",
    thinkFlow: "ThinkFlow",
    unleashPotential: "Раскройте свой когнитивный потенциал с помощью персонализированного обучения на базе ИИ.",
    topicToLearn: "Тема для изучения",
    yourInterests: "Ваши интересы (через запятую)",
    generateExplanation: "Создать объяснение",
    waitingInput: "Ожидание ввода...",
    aiThinking: "ИИ думает...",
    learningGoals: "Цели обучения",
    initializing: "Инициализация ThinkFlow",
    settingUpProfile: "Настройка вашего профиля...",
    demoMode: "ДЕМО РЕЖИМ",
    googleSignIn: "ВОЙТИ ЧЕРЕЗ GOOGLE",
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    encryptionActive: "Квантовое шифрование активно",
    geniusEcosystem: "Экосистема Гениев",
    emailAddress: "Email адрес",
    password: "Пароль"
  },
  uz: {
    hero: "Yaxshiroq o'ylang, tezroq emas.",
    sub: "ThinkFlow — bu sizning miyangizni yodlashdan tushunishga o'tkazadigan global EdTech platformasi.",
    features: "Ichida nima bor?",
    feat1: "Konsept Ustoz: Mavzularni sizning qiziqishlaringiz orqali tushuntiradi.",
    feat2: "Fikrlash Murabbiyi: Savollar orqali yechimni o'zingiz topishingizga yordam beradi.",
    feat3: "Moslashuvchan Trener: Sizning darajangizga mos vazifalar generatori.",
    start: "Boshlash", login: "Kirish", register: "Ro'yxatdan o'tish", logout: "Chiqish",
    dash: "Asosiy", teacher: "Konsept Ustoz", coach: "Fikrlash Murabbiyi", trainer: "Trener",
    wall: "Reyting", profile: "Profil", admin: "Admin",
    save: "Saqlash", reviews: "Sharhlar", history: "Tarix",
    authError: "Xatolik. Ma'lumotlarni tekshiring.",
    writeReview: "Fikringizni yozing", submit: "Yuborish",
    theme: "Mavzu o'zgartirish",
    language: "Til",
    editProfile: "Profilni tahrirlash",
    name: "Ism sharif", bio: "Ma'lumot", update: "Yangilash",
    tasks: "Vazifalar", progress: "Yutuqlar", articles: "Maqolalar", tips: "Maslahatlar", quotes: "Iqtiboslar", leaderboard: "Reyting", settings: "Sozlamalar",
    learn: "O'rganish",
    easy: "Oson", medium: "O'rtacha", challenge: "Qiyin",
    complete: "Bajarildi", pending: "Kutilmoqda",
    xp: "XP", level: "Daraja",
    sat: "SAT Maslahatlari", ielts: "IELTS Maslahatlari",
    satTips: "SAT o'qish strategiyalari, vaqtni boshqarish, matematika usullari.",
    ieltsTips: "IELTS gapirish, yozish, tinglash va o'qish bo'yicha maslahatlar.",
    nextGenAI: "Yangi avlod AI ta'limi",
    beyondGenius: "Daholikdan tashqari",
    heroSub: "ThinkFlow shunchaki chat emas. Bu sizning shaxsiy daholik laboratoriyangiz bo'lib, unda AI aynan siz uchun bilim xaritalarini quradi.",
    demo: "Demo",
    coreEngine: "Asosiy dvigatel",
    coreEngineSub: "Ilg'or neyron arxitekturalari asosida",
    stopMemorizing: "Yodlashni to'xtating.",
    startFlowing: "Tushunishni boshlang.",
    retentionRate: "Eslab qolish darajasi",
    learningSpeed: "O'rganish tezligi",
    secure: "Xavfsiz",
    global: "Global",
    exploreSystem: "Tizimni o'rganish",
    reactorTitle: "AI Reaktori",
    reactorDesc: "Qiziqishlaringiz orqali bilimlarni sintez qiling. Biz javob bermaymiz, biz tushuncha hosil qilamiz.",
    geniusModeTitle: "Daho rejimi",
    geniusModeDesc: "O'rganish ritmingizga moslashadigan interfeys.",
    biometricsTitle: "Miya biometriyasi",
    biometricsDesc: "Haqiqiy vaqtda kognitiv taraqqiyotni kuzatish.",
    hubTitle: "Global Hub",
    hubDesc: "Sayyoradagi eng yaxshi aqllar uchun ekotizim. Birga o'rganing.",
    constructingKnowledge: "Bilimlarni qurish...",
    architectingModel: "Uchun aqliy modelni loyihalash",
    geniusLabSub: "O'zlashtirmoqchi bo'lgan har qanday mavzuni kiriting. Bizning AI qiziqishlaringizdan metafora sifatida foydalanib, maxsus o'rganish yo'lini quradi.",
    initialize: "Ishga tushirish",
    deepUnderstanding: "Chuqur tushunish",
    deepUnderstandingDesc: "Yodlash yo'q. Sof mantiq.",
    personalizedMetaphors: "Shaxsiy metaforalar",
    personalizedMetaphorsDesc: "Fizikani futbol orqali o'rganing.",
    skillMastery: "Mahorat",
    skillMasteryDesc: "Bosqichma-bosqich arxitektura yo'li.",
    knowledgeMap: "Bilim xaritasi",
    newTopic: "Yangi mavzu",
    nodeExplanation: "Tugun tushuntirishi",
    theMetaphor: "Metafora",
    geniusChallenge: "Daho chaqiruvi",
    completeChallenge: "Chaqiriqni bajarish",
    askSidekick: "AI yordamchisidan so'rash",
    architectingMind: "Sizning aqlingizni loyihalash",
    previous: "Oldingi",
    next: "Keyingi",
    askAbout: "Haqida so'rash",
    tipsSub: "Xalqaro imtihonlarni topshirish va fikrlash qobiliyatini rivojlantirishga yordam beradigan ekspert maslahatlari va strategiyalari.",
    generalTips: "Umumiy maslahatlar",
    generalTipsSub: "Samarali o'rganish uchun universal maslahatlar.",
    proTipTitle: "Pro maslahat: Sokratik halqa",
    proTipDesc: "O'rganayotganda shunchaki javobni o'qimang. O'zingizdan uch marta \"Nima uchun?\" deb so'rang. Agar siz mantiqni 5 yoshli bolaga tushuntirib bera olsangiz, demak siz tushunchani haqiqatan ham o'zlashtirgansiz. ThinkFlow sizga ushbu odatni shakllantirishga yordam beradi.",
    reasoning: "Fikrlash",
    logic: "Mantiq",
    mastery: "Mahorat",
    articlesSub: "Asosiy tushunchalar va mulohazalarga chuqur kirib borish.",
    philosophy: "Ta'limning kelajagi ko'proq kitoblar emas, balki yaxshiroq fikrlashdir.",
    philosophySub: "ThinkFlow asosiy falsafasi",
    retentionRateLabel: "Eslab qolish darajasi",
    learningSpeedLabel: "O'rganish tezligi",
    geniusLab: "Daho laboratoriyasi",
    geniusMode: "Daho rejimi",
    searchThoughts: "Fikrlarni qidirish...",
    globalXP: "Global XP",
    masterTopic: "Nimani o'rganmoqchisiz?",
    educationBroken: "An'anaviy ta'lim tizimi buzilgan. U mantiqni emas, yodlashni rag'batlantiradi. ThinkFlow o'yin qoidalarini o'zgartiradi va murakkab tushunchalarni to'g'ridan-to'g'ri neyron yo'llaringizga xaritada ko'rsatish uchun sun'iy intellektdan foydalanadi.",
    navFeatures: "Xususiyatlar",
    navMission: "Missiya",
    navContact: "Bog'lanish",
    versionBadge: "V.2.0 ENDI TAYYOR",
    heroThink: "O'ylash",
    heroBeyond: "Daholikdan",
    heroGenius: "Yuqori",
    coreArchitecture: "Asosiy Arxitektura",
    marqueeText: "MOSLASHUVCHAN TA'LIM • NEYRON ARXITEKTURASI • KVANT MANTIQI • SOKRATIK METOD • 3.5X TEZROQ • MA'LUMOTNI ESLAB QOLISH • DAHO DVIGATELI",
    builtEra: "Uchun qurilgan",
    nextEra: "Yangi Era",
    builtEraSub: "Biz faktlarni o'rgatmaymiz. Biz murakkab tushunchalar va sizning shaxsiy dunyongiz o'rtasida ko'priklar quramiz.",
    joinRevolution: "Inqilobga qo'shiling",
    ourMission: "Bizning Missiyamiz",
    missionStop: "Yodlashni",
    missionMemorizing: "To'xtating.",
    missionStart: "O'sishni",
    missionGrowing: "Boshlang.",
    missionSub: "An'anaviy ta'lim sizni ma'lumotlarni kontekstsiz qabul qilishga majbur qiladi. ThinkFlow qoidalarni o'zgartiradi. Biz sizning qiziqishlaringizni akademik qiyinchiliklarga bog'laymiz va o'rganish nafas olish kabi tabiiy bo'lgan \"Oqim holati\"ni yaratamiz.",
    speedBoost: "Tezlik oshishi",
    retention: "Eslab qolish",
    readyToAscend: "Ko'tarilishga tayyormisiz?",
    privacy: "Maxfiylik",
    security: "Xavfsizlik",
    contactFooter: "Aloqa",
    copyright: "© 2026 INTELLEKT KELAJAGI",
    contactMeSection: "To'g'ridan-to'g'ri bog'laning",
    contactMeSub: "Savollaringiz bormi yoki hamkorlik qilmoqchimisiz? Men doim yangi g'oyalar uchun ochiqman.",
    telegramButton: "Telegramda bog'lanish",
    tasksSub: "Logikangizni rivojlantirish uchun shaxsiy vazifalar.",
    clearAll: "Barchasini o'chirish",
    generateNewTask: "Yangi vazifa yaratish",
    noTasks: "Vazifalar yo'q. Birinchisini yarating!",
    taskAnswerPlaceholder: "Natijani, formulani yoki maxsus tushunchani kiriting...",
    verifying: "Tekshirilmoqda...",
    submitVerify: "Yuborish va tekshirish",
    neuralMapping: "Neyron xaritani qurish...",
    synthesizingNode: "ILMIY TUGUNNI SINTEZ QILISH:",
    systemOptimizing: "TIZIM OPTIMIZATSIYASI",
    systemFailure: "Tizim xatoligi",
    tryAgain: "Qayta urinish",
    rewardLabel: "MUKOFOT",
    geniusAnswerPlaceholder: "Yakuniy javobingizni shu yerga kiriting (masalan, '42', 'NaCl', 'F=ma'). Aniq bo'ling!",
    verifyingAI: "AI tekshirmoqda...",
    submitVerification: "Tekshirishga yuborish",
    nodeMastered: "Tugun o'zlashtirildi",
    geniusModeActive: "DAHO REJIMI FAOLLASHTIRILGAN",
    totalXP: "Jami XP",
    currentLevelLabel: "Joriy daraja",
    tasksDone: "Bajarilgan vazifalar",
    globalRank: "Global daraja",
    progressSub: "Sizning intellektual o'sishingiz real vaqt rejimida.",
    levelLabel: "Daraja",
    nextLevel: "Keyingi daraja",
    xpNextLevel: "Keyingi darajagacha XP",
    growthRate: "O'sish sur'ati",
    dailyStreak: "Kunlik seriya",
    focusScore: "Fokus balli",
    thisWeek: "shu haftada",
    days: "Kun",
    newConversation: "Yangi suhbat",
    chatPlaceholder: "Fikringizni yozing va AI javobini kuting...",
    thinkFlow: "ThinkFlow",
    unleashPotential: "AI-ga asoslangan shaxsiy ta'lim bilan kognitiv salohiyatingizni ishga soling.",
    topicToLearn: "O'rganiladigan mavzu",
    yourInterests: "Sizning qiziqishlaringiz (vergul bilan ajrating)",
    generateExplanation: "Tushuntirish yaratish",
    waitingInput: "Kutilmoqda...",
    aiThinking: "AI o'ylamoqda...",
    learningGoals: "O'quv maqsadlari",
    initializing: "ThinkFlow tayyorlanmoqda",
    settingUpProfile: "Profilingiz sozlanmoqda...",
    demoMode: "DEMO REJIM",
    googleSignIn: "GOOGLE ORQALI KIRISH",
    noAccount: "Hisobingiz yo'qmi?",
    haveAccount: "Hisobingiz bormi?",
    encryptionActive: "Kvant shifrlash faol",
    geniusEcosystem: "Daholar ekotizimi",
    emailAddress: "Email manzili",
    password: "Parol"
  }
};
